name: Update Pending Payments

on:
  repository_dispatch:
    types: [update-pending-data]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update pending-payments.json
        run: |
          echo "$DATA" > pending-payments.json
        env:
          DATA: ${{ github.event.client_payload.data }}

      - name: Commit and Push
        run: |
          git config --global user.name "Tax Bot"
          git config --global user.email "bot@tax.com"
          git add pending-payments.json
          git commit -m "ğŸ” Auto update pending payments"
          git push
